name: Testing application

on:
   push: 
    branches:
      - master
    
    pull_request:
      branches:
        - master

jobs:
  stay-update:
      runs-on: ubuntu-latest
      steps:
        - name: Setup node js
          uses: actions/setup-node@v4
        - name: Run node js code
          run: node -e "console.log('Hello world program')"